FROM golang:1.12-alpine as build

RUN apk add --no-cache git

# Set the Current Working Directory inside the container
WORKDIR /app/go-drawing

# We want to populate the module cache based on the go.{mod,sum} files.
ENV GOPROXY https://goproxy.cn
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN chmod -R 777 upload

# Build the Go app
RUN go build -o ./bin/drawing .
RUN git clone https://xiezhiqiang%40scrmtech.com:Waj33040!@e.coding.net/zqbc-scrm-new/scrm/go_conf.git ./go_conf



FROM alpine:3.12 as prod

WORKDIR /app/go-drawing

# 设置时区为上海gca
RUN echo -e https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/ > /etc/apk/repositories && apk update && apk add  curl bash tree tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

RUN mkdir ./runtime

RUN mkdir ./upload

RUN chmod -R 777 upload


RUN chmod -R 777 ./runtime

COPY --from=build /app/go-drawing/font/ /app/go-drawing/font/
COPY --from=build /app/go-drawing/bin/drawing /app/go-drawing/bin/
COPY --from=build /app/go-drawing/go_conf/dev/drawing/conf/ /app/go-drawing/conf/



# This container exposes port 8080 to the outside world
EXPOSE 8007

# Run the binary program produced by `go install`
ENTRYPOINT ["./bin/drawing"]